# Generated by Django 3.1 on 2022-03-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=300)),
                ('can_be_sold_in', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
