# Generated by Django 3.1 on 2022-03-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredients_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='can_be_sold_in',
            new_name='can_be_sold_in_china',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='type',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='non_comedogenic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='vegan',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
